<h1>Escolha seus produtos e realize sua compra!</h1>

<section class="produtos">
    <?php foreach($this->view->dados as $i=>$dados){ ?>
        <div class="produto">
            <img src="imagens/<?php echo $dados['imagem']?>" alt=""><br>
            <span><?php echo $dados['nome'].' - R$ '.$dados['preco'] ?></span><br>

            <form action="/carrinho?adicionar=1" method="POST">
                <input type="hidden" name="id" value="<?php echo $dados['id'] ?>">
                <input type="number" name="qtd" id="" min="1" max="15" value="1"><br>
                <button type="submit">Adicionar</button>
            </form>
        </div>
    <?php } ?>
</section>

<a href="/carrinho">Ir para seu carrinho</a>
<br><br>
<a href="/logout">Sair</a>